### ISSUE TITLE
ERROR  connect ECONNREFUSED ::1:3333

### ISSUE THREAD

**Issue by monstorbak** [BOMIST/bomist-scripts#1]
Fresh install of BOMIST, node.js + dependencies, and yarn. Working from the "Sample" workspace provided by BOMIST.

API server is running on localhost and I'm able to query successfully via web browser.

Attempting to run `yarn ts src/owned_inventory.ts` results in the output below

```
$ yarn ts src/owned_inventory.ts
yarn run v1.22.19
$ ts-node src/owned_inventory.ts

 ERROR  connect ECONNREFUSED ::1:3333

  at Function.AxiosError.from (node_modules\axios\lib\core\AxiosError.js:89:14)
  at RedirectableRequest.handleRequestError (node_modules\axios\lib\adapters\http.js:515:25)
  at RedirectableRequest.emit (node:events:513:28)
  at RedirectableRequest.emit (node:domain:489:12)
  at ClientRequest.eventHandlers.<computed> (node_modules\follow-redirects\index.js:14:24)
  at ClientRequest.emit (node:events:513:28)
  at ClientRequest.emit (node:domain:489:12)
  at Socket.socketErrorListener (node:_http_client:496:9)
  at Socket.emit (node:events:513:28)
  at Socket.emit (node:domain:489:12)

D:\GitHub\bomist-scripts\api\js\node_modules\axios\lib\core\AxiosError.js:89
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError: connect ECONNREFUSED ::1:3333
    at Function.AxiosError.from (D:\GitHub\bomist-scripts\api\js\node_modules\axios\lib\core\AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (D:\GitHub\bomist-scripts\api\js\node_modules\axios\lib\adapters\http.js:515:25)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at ClientRequest.eventHandlers.<computed> (D:\GitHub\bomist-scripts\api\js\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at Socket.socketErrorListener (node:_http_client:496:9)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12) {
  port: 3333,
  address: '::1',
  syscall: 'connect',
  code: 'ECONNREFUSED',
  errno: -4078,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      'User-Agent': 'axios/1.1.2',
      'Accept-Encoding': 'gzip, deflate, br',
      [Symbol(defaults)]: [Object]
    },
    baseURL: 'http://localhost:3333',
    method: 'get',
    url: '/storage',
    data: undefined
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/storage',
      method: 'GET',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: 'localhost',
      port: '3333',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/storage'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 0,
    _requestBodyBuffers: [],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'GET /storage HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/1.1.2\r\n' +
        'Accept-Encoding: gzip, deflate, br\r\n' +
        'Host: localhost:3333\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/storage',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kEndCalled)]: true,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:3333/storage',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect ECONNREFUSED ::1:3333
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1487:16) {
    errno: -4078,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 3333
  }
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rasgo-cc** [comment]
@monstorbak hey Nick! Sorry for the big delay. It looks like the script couldn't reach the server. Any chance your ran the script through Windows Subsystem for Linux (WSL)? If that's so you'll have to bind the server to `0.0.0.0` (instead of  `localhost`), check your local IP (e.g. with `ipconfig`) and then use that IP on the script instead (i.e. edit [this line](https://github.com/BOMIST/bomist-scripts/blob/main/api/js/src/owned_inventory.ts#L27)).

Something like this: 
```
$ ipconfig

Ethernet adapter vEthernet (WSL):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : xxxxx
   IPv4 Address. . . . . . . . . . . : 123.45.678.1
```

And then, on WSL (and assuming the port is `3333`):
```
$ curl 123.45.679.1:3333

{"bomist":{"app":{"version":"2.10.0-beta.12"},"api":{"swaggerUI":"http://localhost:3333/_swagger_ui","swaggerJSON":"http://localhost:3333/swagger.json"},"user":{"email":"your@email.com"},"workspace":{"team":false,"name":"Sample"}}}
```
